name: CUTEst Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran liblapack-dev
    
    - name: Setup CUTEst directories
      run: |
        # Create base directory
        mkdir -p cutest_build
        cd cutest_build
        
        # Clone the necessary repositories
        git clone https://github.com/ralna/ARCHDefs ./archdefs
        git clone https://github.com/ralna/SIFDecode ./sifdecode
        git clone https://github.com/ralna/CUTEst ./cutest
        
        # Create the mastsif directory and get problems
        mkdir -p ./mastsif
        git clone https://github.com/ralna/SIFDecode ./tmp_sif
        cp ./tmp_sif/sif/*.SIF ./mastsif/ || true
        rm -rf ./tmp_sif
        
        # Set environment variables
        echo "ARCHDEFS=$PWD/archdefs" >> $GITHUB_ENV
        echo "SIFDECODE=$PWD/sifdecode" >> $GITHUB_ENV
        echo "MASTSIF=$PWD/mastsif" >> $GITHUB_ENV
        echo "CUTEST=$PWD/cutest" >> $GITHUB_ENV
        echo "MYARCH=pc64.lnx.gfo" >> $GITHUB_ENV
    
    - name: Install CUTEst
      run: |
        # Set environment variables (needed again inside this step)
        export ARCHDEFS=$ARCHDEFS
        export SIFDECODE=$SIFDECODE
        export MASTSIF=$MASTSIF
        export CUTEST=$CUTEST
        export MYARCH=$MYARCH
        
        # Build and install
        cd $ARCHDEFS
        ./install_optrove
        
        cd $SIFDECODE
        ./install_optrove -s
        
        cd $CUTEST
        ./install_optrove -s
        
        # Add to PATH and LD_LIBRARY_PATH
        echo "$CUTEST/bin" >> $GITHUB_PATH
        echo "$SIFDECODE/bin" >> $GITHUB_PATH
        echo "$CUTEST/objects/$MYARCH/double" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=$CUTEST/objects/$MYARCH/double:$LD_LIBRARY_PATH" >> $GITHUB_ENV
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        
        # Install pycutest with proper environment variables
        export ARCHDEFS=$ARCHDEFS
        export SIFDECODE=$SIFDECODE
        export MASTSIF=$MASTSIF
        export CUTEST=$CUTEST
        export MYARCH=$MYARCH
        python -m pip install pycutest
        
        # Install your package dependencies (modify as needed)
        python -m pip install -e .
    
    - name: Verify installation
      run: |
        # List installed directories to verify
        echo "=== CUTEst directories ==="
        ls -la $CUTEST/bin || echo "CUTEst bin directory not found"
        ls -la $SIFDECODE/bin || echo "SIFDecode bin directory not found"
        
        # Check if we can import pycutest
        python -c "import pycutest; print('CUTEst successfully installed')"
    
    - name: Run tests
      run: |
        # Run your tests that use CUTEst (modify as needed)
        python -m pytest tests/