name: Run tests

on:
  push:
  pull_request:
    branches: [ main ]

jobs:
  test-problem-definition:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test with pre-built image
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace \
            johannahaffner/pycutest:latest \
            bash -c "cd /workspace && pip install -e . && pytest tests/test_problem.py"

  test-problem-runtime:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test with pre-built image
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace \
            johannahaffner/pycutest:latest \
            bash -c "cd /workspace && pip install -e . && pytest tests/test_runtime.py"
