name: Run tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran liblapack-dev
    
    - name: Install CUTEst
      run: |
        # Create installation directory
        mkdir -p ~/cutest_install
        cd ~/cutest_install
        
        # Set environment variables for CUTEst
        export ARCHDEFS=$PWD/archdefs
        export SIFDECODE=$PWD/sifdecode
        export MASTSIF=$PWD/mastsif
        export CUTEST=$PWD/cutest
        export MYARCH=pc64.lnx.gfo
        
        # Create directories
        mkdir -p $ARCHDEFS $SIFDECODE $MASTSIF $CUTEST
        
        # Download and install CUTEst
        curl -fsSL https://raw.githubusercontent.com/jfowkes/pycutest/master/.install_cutest.sh > install_cutest.sh
        chmod +x install_cutest.sh
        ./install_cutest.sh
    
    - name: Set CUTEst environment
      run: |
        echo "ARCHDEFS=~/cutest_install/archdefs" >> $GITHUB_ENV
        echo "SIFDECODE=~/cutest_install/sifdecode" >> $GITHUB_ENV
        echo "MASTSIF=~/cutest_install/mastsif" >> $GITHUB_ENV
        echo "CUTEST=~/cutest_install/cutest" >> $GITHUB_ENV
        echo "MYARCH=pc64.lnx.gfo" >> $GITHUB_ENV
        echo "LD_LIBRARY_PATH=~/cutest_install/cutest/objects/pc64.lnx.gfo/double:$LD_LIBRARY_PATH" >> $GITHUB_ENV
        echo "$HOME/cutest_install/cutest/bin:$HOME/cutest_install/sifdecode/bin" >> $GITHUB_PATH
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest
        python -m pip install pycutest
        
        # Install your package dependencies (modify as needed)
        python -m pip install -e .
    
    - name: Run tests
      run: |
        # Verify CUTEst is accessible
        python -c "import pycutest; print('CUTEst successfully installed')"
        
        # Run your actual tests (modify as needed)
        python -m pytest tests/